### ISSUE TITLE
Not Working With SCM Screwdriver

### ISSUE THREAD

**Issue by simpson409** [VazkiiMods/Morph-o-Tool#32] opened 2016-11-30 14:45 UTC

**Comment by werwerwsx** [comment] 2016-12-04 23:26
The screwdriver from SCM takes damage which I believe disqualifies a tool from being added to Morph, since keeping track of damage/removing the tool when it broke either isn't coded yet or Vazkii isn't planning on coding in.

**Comment by Vazkii** [comment] 2016-12-04 23:34
You are completely wrong. This has to do with SCM not having its own blocks
but rather having them as McMultipart pieces.

**Comment by werwerwsx** [comment] 2016-12-04 23:37
Ah, my apologies.

**Comment by gmoff01** [comment] 2017-01-05 19:27
Does the reason mentioned above mean that this can never work, or just that it will need later implementation?

**Comment by gmoff01** [comment] 2017-01-05 19:31
Or maybe a config alias for the micropart system?

**Comment by PapiDimmi** [comment] 2017-03-28 17:38
Dupe of #27 and #15.

**Comment by Uraneptus** [comment] 2024-08-17 15:43
If this is still relevant in the newest version, please open a new issue

**Closed by Uraneptus** 2024-08-17 15:43 UTC
Labels: unsupported version
